name: DevSecOps Node App CI

on:
  push:
    branches:
      - main
      # - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "devsecops-node-app"
          path: "./"
          format: "HTML"

      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: OWASP Dependency Check Report
          path: ${{github.workspace}}/reports

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t devsecops-node-app .
