name: Deploy Node.js App to EC2 with PM2 (Node 20)

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy and Start App on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Install Node.js v20 (Amazon Linux 2)
            curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash -
            sudo yum install -y nodejs

            # Install Git (if not already present)
            sudo yum install -y git

            # Install PM2 globally
            sudo npm install -g pm2

            # Remove any previous app directory
            rm -rf ~/devsecops-node-app

            # Clone latest version from GitHub
            git clone https://github.com/prabhtz/devsecops-sample-integration.git ~/devsecops-node-app

            # Navigate into project
            cd ~/devsecops-node-app

            # Install Node dependencies
            npm install

            # Stop old PM2 app if it exists
            pm2 delete app || true

            # Start the app using PM2
            pm2 start src/index.js --name app

            # Save PM2 process list for auto-restart
            pm2 save
