name: Terraform Plan (with Linting and Security)

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  terraform-plan:
    name: Terraform Plan Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
          # github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run TFLint
        run: |
          tflint --init
          tflint

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          version: latest
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          soft_fail_commenter: true
          working_directory: "."

      - name: Terraform Plan
        run: terraform plan -no-color
